sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t leonidkuznetsov/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true leonidkuznetsov/docker-react npm run test -- --coverage
